In [ ]:
# vector --> tek satırlı array'ler
# matrix rows x columns bulunan arrayler. nested gibi
# arraylerde vectorel işemleri (ayni indexe sahip elementleri bir biri ile işleme sokmak) rahatlıkla yapariz.

# Broadcasting 
 

#axis 0 --> satırlara gore islem yapma. altalta
#axis 1 --> sutunlara gore islem yapma -> yanyana


#  ---> ARRAY İCERİSİNE AYNI TURDE ELEMAN KABUL EDER. 
#  ICERISINDE FLOAT VE INT ELEMENT OLSA DA BIZE FLOAT OLARAK VERİR

# !pip install numpy yazarak numpy yukleriz ardından -import numpy as np- olarak kullaniriz.
# np.array() --> array olusturma yontemi. içine list ya da istediğimiz elemanlari yazarak olusturabiliriz.
# array_adi.shape --> bize seklini verir
# array_adi.reshape(satir, sutun) --> yeniden arrayi şekillendirmek için kullanilir.
# array_adi.reshape(-1)

#ndmin istedigin boyuta ceviriyor, ndim ise kac boyutlu oldugunu veriyor
# n = adet

# dim= dimention


In [6]:
import matplotlib.pyplot as plt

In [8]:
import numpy as np

In [29]:
array_1d = np.array([1,2,3,4,5,6,7,8,9])
array_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
array_1d.shape

(9,)

In [30]:
array_1d.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
array_1d.shape

(9,)

AttributeError: module 'numpy' has no attribute 'array_1d'

In [25]:
a=[1,2,3,4]
b=[4,3,2,1]

In [26]:
list=[]
for x,y in zip(a,b):
    list.append(x*y)
print(list)    

[4, 6, 6, 4]


In [27]:
np.array(a).dtype

dtype('int32')

In [30]:
c_arr=np.array(a)

In [31]:
print(c_arr.dtype)

int32


In [32]:
d_arr=np.array(a,dtype=float)

In [33]:
d_arr.dtype

dtype('float64')

In [36]:
np.shape(c_arr)

(4,)

In [11]:
my_array = np.array([1,2,3,4,5,6,7,8,9])
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.shape(a)

(4,)

In [17]:
my_list2=[[1,2,3],[4,5,6,],[7,8,9],[10,11,12]]

In [23]:
my_array=np.array(my_list2)
my_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [21]:
 my_array.shape   

(4, 3)

In [38]:
my_array.reshape(3,4) ########################

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
my_array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
np.reshape(my_array,(3,4))################

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
my_list2=[1,2,3,4,5,6,7,8,9,10,11,12]

In [51]:
arr2=np.array(my_list2)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [53]:
arr2.reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
arr2.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
arr2 = np.array(arr2, ndmin=4)
arr2

array([[[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]]])

In [60]:
arr2.ndim

4

In [61]:
np.ndim(arr2)

4

In [67]:
str_arr = [1,2,3.4,5.5,"a"]
str_arr = np.array(str_arr)
str_arr
print(type(str_arr))

<class 'numpy.ndarray'>


In [69]:
str_arr.dtype

dtype('<U32')

In [71]:
 np.array(str_arr,dtype=float)

ValueError: could not convert string to float: 'a'

In [78]:
arr =np.array([1,2,3.4,5.5])
arr.dtype

dtype('float64')

In [81]:
arr = arr.astype("i")
arr.dtype

dtype('int32')