In [5]:
!pip install numpy

In [3]:
import numpy as np

In [7]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

In [9]:
import time

In [10]:
time.time()

1680207963.098051

In [13]:
start = time.time()

In [14]:
start

1680208036.743045

In [22]:
numpy ile list calisma hızı kıyaslama
size = 10_000_000
l1 = range(size)
l2 = range(size)
a1 = np.arange(size)
a2 = np.arange(size)

start= time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took : " ,(time.time() - start) * 1_000)

start = time.time()
result = a1+ a2
print("numpy took :  ", (time.time() - start) * 1_000 )


python list took :  2008.9616775512695
numpy took :   150.90489387512207


In [24]:
#  numpy ile list calisma hızı kıyaslama HOCANİNKİ
size = 10000000
l1= range(size)
l2= range(size)
a1 = np.arange(size)
a2 = np.arange(size)
start = time.time()
result = [(x+y) for x, y in zip(l1,l2)]
print("python list took: ", (time.time() - start) * 1000)
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time() - start) * 1000)

python list took:  2030.4477214813232
numpy took:  154.90031242370605


In [26]:
import sys

In [27]:
sys.getsizeof(5)

28

In [28]:
sys.getsizeof(55555)

28

In [29]:
sys.getsizeof("a")

50

In [30]:
sys.getsizeof("aaa")

52

In [34]:
l = range(1000)

print(sys.getsizeof(5))
print(sys.getsizeof(5) * len(l))



a = np.arange(1000)

print(a.itemsize)
print(a.itemsize * a.size)

28
28000
4
4000


In [36]:
l = range(1000)
print(sys.getsizeof(5))
print(sys.getsizeof(5) * len(l))
a=np.arange(1000)
print(a.itemsize)
print(a.itemsize * a.size)

28
28000
4
4000


In [38]:
a = [1,2,3,4]
b = [4,3,2,1]

In [44]:
a = [1,2,3,4]
b = [4,3,2,1]
l = []
for i in range(len(a)):
    l.append(a[i]*b[i])
print(l)

[4, 6, 6, 4]


In [45]:
[i * j for i, j in zip(a, b)]


[4, 6, 6, 4]

In [46]:
a1 = np.array(a)
a2 = np.array(b)

In [47]:
a1*a2

array([4, 6, 6, 4])

In [48]:
a1 / a2

array([0.25      , 0.66666667, 1.5       , 4.        ])

In [49]:
a1 - a2

array([-3, -1,  1,  3])

In [50]:
a1 + a2

array([5, 5, 5, 5])

In [52]:
list=[]
for x,y in zip(a,b) :
    list.append(x*y)
print(list)    


[4, 6, 6, 4]


# array

In [53]:
mylist = [1,2,3]
mylist

[1, 2, 3]

In [54]:
np.array(mylist)

array([1, 2, 3])

In [55]:
np.array([1,2,3])

array([1, 2, 3])

In [56]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [59]:
mylist2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [61]:
myarray = np.array(mylist2)
myarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# 2 shape & reshape

In [63]:
myarray.shape

(4, 3)

In [70]:
myarray.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
myarray.reshape(4,4)  # hata bu sekilde ayiramiyor

ValueError: cannot reshape array of size 12 into shape (4,4)

In [74]:
myarray.reshape(12).reshape(2,2,3) # reshape uzerine reshape uyguladık. 2 katmanli 2 satirli 3 sutunlu

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
myarray.reshape(-1,4) # satiri sen ayarla, 4 sutun olsun

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
myarray.reshape(3,-1) #satiri 3 olsun , sutunu sen ayarla 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 3 ndmin

In [9]:
mylist = list(range(0,12))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [10]:
myarray = np.array(mylist)
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
myarray.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
myarray = np.array(mylist,ndmin=4)  # calismadi hoca bakacak
myarray

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]]])

# 4 dtype & astype